version: '3.3'
services:
    angular-ci:
      hostname: localhost
      container_name: angular-app-container
      build:
        context: .
        dockerfile: Dockerfile
      image: angular-app-image
      ports:
        - '4200:80'
    cypress-ci:
        hostname: localhost
        container_name: cypress-container
        build:
            context: .
            dockerfile: Dockerfile-cypress
        image: cypress-image
        depends_on:
            - angular-ci
        network_mode: 'host'
        
