FROM cypress-test-image

COPY . .

ENV NODE_ENV dev

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get install -y nodejs

RUN npm install cypress --save-dev

CMD ["npx", "cyprus", "run"]
